<?php

namespace App;

/**
 * GeminiClient (with OpenAI Gateway Support)
 * Sends messages to Google natively, OR to OpenAI-compatible
 * gateways (like SumoPod) depending on the BASE_URL in .env.
 */
class GeminiClient
{
    private string $apiKey;
    private string $model;
    private string $apiUrl;
    private bool   $isGoogleMode;

    /**
     * In-memory chat history for the current process run.
     * Stored in a generic format, translated on the fly for the target API.
     * Format: [ ['role' => 'user'|'model', 'text' => '...', 'image' => '...', 'mime' => '...'], ... ]
     */
    private array $history = [];

    /** System instruction built from bot_character.php */
    private string $systemInstruction;

    public function __construct()
    {
        $this->apiKey  = $_ENV['GEMINI_API_KEY'] ?? '';
        $this->model   = $_ENV['GEMINI_MODEL']   ?? 'gemini-2.0-flash';
        $baseUrl       = rtrim($_ENV['GEMINI_BASE_URL'] ?? 'https://generativelanguage.googleapis.com', '/');
        
        $this->isGoogleMode = str_contains($baseUrl, 'googleapis.com');

        if ($this->isGoogleMode) {
            $this->apiUrl = "{$baseUrl}/v1beta/models/{$this->model}:generateContent?key={$this->apiKey}";
        } else {
            // OpenAI-compatible gateway (SumoPod, etc.)
            $this->apiUrl = "{$baseUrl}/v1/chat/completions";
        }

        $this->systemInstruction = $this->buildSystemInstruction();
    }

    public function chat(
        string  $userMessage,
        ?string $imageBase64 = null,
        ?string $mimeType    = 'image/jpeg'
    ): string {
        // Record user turn in internal generic format
        $this->history[] = [
            'role'  => 'user',
            'text'  => $userMessage !== '' ? $userMessage : 'What do you see in this image?',
            'image' => $imageBase64,
            'mime'  => $mimeType,
        ];

        if ($this->isGoogleMode) {
            $reply = $this->chatViaGoogleApi();
        } else {
            $reply = $this->chatViaOpenAiGateway();
        }

        // Record model turn
        $this->history[] = [
            'role' => 'model',
            'text' => $reply,
        ];

        return $reply;
    }

    public function resetHistory(): void
    {
        $this->history = [];
    }

    /**
     * Intercept and process any [MEMORY: fact] or [REMIND: time | message]
     * blocks generated by the model before returning the final text to the user.
     */
    private function processAndStripCommands(string $text): string
    {
        // 1. Process REMINDERS
        $text = preg_replace_callback('/\[REMIND:\s*([^|]+)\s*\|\s*(.*?)\]/i', function($matches) {
            $time = trim($matches[1]);
            $msg  = trim($matches[2]);
            \App\Database::addReminder($time, $msg);
            return ""; // Strip it from the final text
        }, $text);

        // 2. Process MEMORIES
        $text = preg_replace_callback('/\[MEMORY:\s*(.*?)\]/i', function($matches) {
            $fact = trim($matches[1]);
            \App\Database::addMemory($fact);
            return ""; // Strip it from the final text
        }, $text);

        return trim($text);
    }

    // ── NATIVE GOOGLE API IMPLEMENTATION ────────────────────────────
    private function chatViaGoogleApi(): string
    {
        $contents = [];
        foreach ($this->history as $turn) {
            $parts = [];
            if (!empty($turn['image'])) {
                $parts[] = [
                    'inline_data' => [
                        'mime_type' => $turn['mime'],
                        'data'      => $turn['image'],
                    ],
                ];
            }
            if (!empty($turn['text'])) {
                $parts[] = ['text' => $turn['text']];
            }
            $contents[] = [
                'role'  => $turn['role'],
                'parts' => $parts,
            ];
        }

        $payload = [
            'system_instruction' => [
                'parts' => [['text' => $this->systemInstruction]],
            ],
            'contents'           => $contents,
            'generationConfig'   => [
                'temperature'     => 0.85,
                'maxOutputTokens' => 1024,
            ],
        ];

        return $this->executeRequest($payload, function($data) {
            $text = $data['candidates'][0]['content']['parts'][0]['text'] ?? null;
            if ($text !== null) {
                return $this->processAndStripCommands($text);
            }
            return null;
        });
    }

    // ── OPENAI-COMPATIBLE GATEWAY IMPLEMENTATION (E.G. SUMOPOD) ─────
    private function chatViaOpenAiGateway(): string
    {
        $messages = [];
        
        // System prompt first
        $messages[] = [
            'role'    => 'system',
            'content' => $this->systemInstruction,
        ];

        foreach ($this->history as $turn) {
            $mappedRole = $turn['role'] === 'model' ? 'assistant' : 'user';

            if (!empty($turn['image'])) {
                // OpenAI vision format
                $imageUrl = "data:{$turn['mime']};base64,{$turn['image']}";
                $content  = [];

                if (!empty($turn['text'])) {
                    $content[] = ['type' => 'text', 'text' => $turn['text']];
                }
                $content[] = [
                    'type'      => 'image_url',
                    'image_url' => ['url' => $imageUrl],
                ];

                $messages[] = ['role' => $mappedRole, 'content' => $content];
            } else {
                $messages[] = ['role' => $mappedRole, 'content' => $turn['text']];
            }
        }

        $payload = [
            'model'       => $this->model,
            'messages'    => $messages,
            'temperature' => 0.85,
            'max_tokens'  => 1024,
        ];

        return $this->executeRequest($payload, function($data) {
            $text = $data['choices'][0]['message']['content'] ?? null;
            if ($text !== null) {
                return $this->processAndStripCommands($text);
            }
            return null;
        }, ['Authorization: Bearer ' . $this->apiKey]);
    }

    // ── HTTP HELPER ─────────────────────────────────────────────────
    private function executeRequest(array $payload, callable $parseReply, array $extraHeaders = []): string
    {
        $headers = array_merge(['Content-Type: application/json'], $extraHeaders);

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,            $this->apiUrl);
        curl_setopt($ch, CURLOPT_POST,           true);
        curl_setopt($ch, CURLOPT_POSTFIELDS,     json_encode($payload));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_HTTPHEADER,     $headers);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        $data = json_decode($response, true) ?: [];

        // Log everything
        $usage        = $data['usageMetadata'] ?? $data['usage'] ?? [];
        $promptTokens = $usage['promptTokenCount']     ?? $usage['prompt_tokens']     ?? 'N/A';
        $outputTokens = $usage['candidatesTokenCount'] ?? $usage['completion_tokens'] ?? 'N/A';
        $totalTokens  = $usage['totalTokenCount']      ?? $usage['total_tokens']      ?? 'N/A';
        $apiType      = $this->isGoogleMode ? 'Native Google' : 'OpenAI Gateway';

        $logLines = [
            "── API Call ({$apiType}) ────────────────────",
            "URL         : {$this->apiUrl}",
            "HTTP Code   : $httpCode",
            "Model       : {$this->model}",
            "Prompt tok  : $promptTokens",
            "Output tok  : $outputTokens",
            "Total tok   : $totalTokens",
        ];

        if ($httpCode !== 200) {
            $logLines[] = "Error Resp  : " . substr(str_replace("\n", " ", $response), 0, 500);
        }

        $logLines[] = "─────────────────────────────────────────────\n";

        file_put_contents(
            __DIR__ . '/log/debug.log',
            implode("\n", $logLines),
            FILE_APPEND
        );

        $reply = $parseReply($data);
        return $reply ? trim($reply) : "Sorry, I couldn't come up with a response right now.";
    }

    // ── CONFIGURATION HELPER ────────────────────────────────────────
    private function buildSystemInstruction(): string
    {
        $char = require __DIR__ . '/../config/bot_character.php';

        $name       = $char['name']                       ?? 'Bot';
        $backstory  = $char['backstory']                  ?? '';
        $tone       = $char['personality']['tone']        ?? 'friendly';
        $emojiStyle = $char['personality']['emoji_style'] ?? 'minimal';
        $language   = $char['personality']['language']    ?? 'en';

        // Load dynamic details for prompt
        date_default_timezone_set('Asia/Jakarta');
        $currentDate = date('Y-m-d H:i:s');
        
        // Example dynamic date for the system prompt
        $currentDateExpected = date('Y-m-d H:i:s', strtotime('+1 hour'));

        try {
            $savedMemories = \App\Database::getAllMemoriesFormatted();
        } catch (\Exception $e) {
            $savedMemories = "No memories saved yet. (DB Error)";
        }

        return <<<EOT
You are {$name}, a personal AI assistant with the following backstory:

{$backstory}

Personality guidelines:
- Tone: {$tone}
- Emoji usage: {$emojiStyle} (none = no emoji, minimal = a few when appropriate, expressive = freely)
- Reply language: {$language}
- You are talking exclusively with your owner/creator.
- Keep replies concise and conversational.
- When the user sends an image, comment on it naturally in character.
- Never break character. You are always {$name}.

=== IMPORTANT DATABASE INSTRUCTIONS ===
If the user tells you to remember a fact about them or about the conversation, save it by outputting the exact string: `[MEMORY: The fact to remember]`. Do not use brackets around the fact itself.
Example: `[MEMORY: The user has a pet dog named Max.]`

If the user asks you to set an alarm or reminder, save it by outputting the exact string: `[REMIND: YYYY-MM-DD HH:MM:00 | The reminder message]`. 
The current date and time in Asia/Jakarta is: {$currentDate}. Make sure the time you schedule is calculated exactly relative to this current time.
Example: `[REMIND: {$currentDateExpected} | Remind the user to call Mom]`

=== SAVED MEMORIES ABOUT THE USER ===
{$savedMemories}
EOT;
    }
}
